services:
  df-aggregator:
    image: docker.io/dubrsl/df-aggregator:latest
    restart: always
    command: /root/df-aggregator/df-aggregator.py --debug --database=/var/lib/df-aggregator/databasename.db --receivers=/root/df-aggregator/receivers.txt --ip=0.0.0.0 --port=8080
    # group-add: keep-groups
    environment:
      - TZ=EET
    ports:
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - var_lib_df-aggregator:/var/lib/df-aggregator
      - ./receivers.txt:/root/df-aggregator/receivers.txt:z

volumes:
  var_lib_df-aggregator:
